# Generated by Django 5.1.6 on 2025-08-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='cdr',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='وضعیت'),
        ),
    ]
