# Generated by Django 5.1.6 on 2025-08-01 16:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0006_alter_brand_image_name_alter_product_image_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درج')),
                ('favorite_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_user1', to=settings.AUTH_USER_MODEL, verbose_name='کاربر علاقه مند')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_product', to='products.product', verbose_name='کالا')),
            ],
            options={
                'verbose_name': 'علاقه',
                'verbose_name_plural': 'علاقه مندی ها',
            },
        ),
        migrations.CreateModel(
            name='Scoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registerdate', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درج')),
                ('score', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_product', to='products.product', verbose_name='کالا')),
                ('scoring_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorinf_user1', to=settings.AUTH_USER_MODEL, verbose_name='امتیاز دهنده')),
            ],
            options={
                'verbose_name': 'امتیاز',
                'verbose_name_plural': 'امتیازات',
            },
        ),
    ]
