# Generated by Django 5.1.6 on 2025-08-03 15:11

import django.db.models.deletion
import django.utils.timezone
import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_brand_image_name_alter_product_image_name_and_more'),
        ('sf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_title1', models.CharField(blank=True, max_length=500, null=True, verbose_name='متن اول')),
                ('slider_title2', models.CharField(blank=True, max_length=500, null=True, verbose_name='متن دوم')),
                ('slider_title3', models.CharField(blank=True, max_length=500, null=True, verbose_name='متن سوم')),
                ('image_name', models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='تصویراسلاید')),
                ('slider_link', models.URLField(blank=True, null=True, verbose_name='لینک')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='وضعیت فعال/غیرفعال')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ اخرین بروزرسانی')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_slider', to='products.product', verbose_name='اسلایدر محصول')),
            ],
            options={
                'verbose_name': 'اسلاید',
                'verbose_name_plural': 'اسلایدها',
            },
        ),
    ]
